### ISSUE TITLE
Brak WS-FileRepoService

### ISSUE THREAD

**Issue by jaszczykj** [wzychla/OldMusicBox.ePUAP.Client#3]
Brak implementacji usługi WS-FileRepoService 
https://ws.epuap.gov.pl/repo-ws-ext/FileRepoService/WEB-INF/wsdl/filerepo.wsdl

Bez niej usługi WS-Pull oraz WS-Skrytka są nie do wykorzystania w praktyce. 
Jaka jest szansa na dodanie WS-FileRepoService?

**Comment by jaszczykj** [comment]
już nie aktualne - dodane w fork-u

**Comment by wzychla** [comment]
Integrator, który korzysta z dotychczasowej usługi nie potrzebował WS-FileRepoService, najwyraźniej nie korzysta z "dużych plików". Mimo tego że kod jest używany we wdrożeniu produkcyjnym. 

Proszę o pozostawienie śladu w postaci krótkiego opisu scenariusza, w którym usługa jest potrzebna w połączeniu z WS-Pull i WS-Skrytka, mogłoby to pomóc przyszłym integratorom (czyli kiedy samo WS-Pull/WS-Skrytka nie wystarcza).

Samo dodanie usługi istotnie powinno być proste, struktura kodu powinna być wystarczająco czytelna.

**Comment by jaszczykj** [comment]
już dodałem implementację WS-FileRepoService - proszę sprawdzić w Fork-u
Scenariusz dla integratora: [Punkt 3 Przykladowy proces]( https://epuap.gov.pl/wps/wcm/connect/02dae4ec-c535-457f-bfce-a0aa6f45b4d7/Instrukcja+integratora+-+obs%C5%82uga+du%C5%BCych+plik%C3%B3w+v1.2.pdf?MOD=AJPERES)

Z tego co się orientuje, to każda nowa skrzynka oraz każdy nowy formularz ma domyślnie włączony obsługę dużych plików.

**Comment by wzychla** [comment]
Dziękuję. Dodam modele usługi i klasę usługi do głównego repo, na pewno komuś jeszcze się przyda. Po dodaniu zamknę zgłoszenie.

**Comment by wzychla** [comment]
Dodalem przy okazji ostatniego commita, proszę o informację czy można zamknąć zgłoszenie.

**Comment by jaszczykj** [comment]
sprawdzę przy okazji, zamykam
